POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "After refactory",
    "author": "Fullstack Dude 3000",
    "url": "http://www.stackoverflow.com",
    "likes": "999"
}