POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvaW1paWtvIiwiaWQiOiI1ZWU4N2UwY2Y4MjE2OTBjOWMwMWVkYTMiLCJpYXQiOjE1OTIyOTUwNjB9.w-v2V-AvNA9wiTO7ZD84vliFmfEY3a0pwbEQ0RbjyPE

{
    "title": "There is your test test",
    "user": "toimiiko",
    "author": "Tommi Toimii",
    "url": "http://www.yolo.com",
    "likes": "6",
    "userId": "5f259886a5dc8e15a0ad13e5"
}